apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myreplicaset
  labels:
    replica: jenkinsreplica
spec:
  replicas: 2
  selector:
    matchLabels:
      usepods: mypodnew
  template:
    metadata: 
       name: jenkinspod
       labels: 
         usepods: mypodnew
    spec: 
      containers:
        - image: jenkins/jenkins:lts
          name: jenkins    
